### ISSUE TITLE
AwesomeOpenSource

### ISSUE THREAD

**Issue by jeffreyjackson** [razum2um/awesome-clojure#26]
We are creating a github org for all awesome open source repos. I am working with a few individuals who are also managing their own awesome repos, and I think to gain more traction we need to work together. What are your thoughts about collectively moving your awesome repos to https://github.com/AwesomeOpenSource

The idea is that visibility for these repos would be increased due to more traffic to the org. What are your thoughts? Let me know if there is anything you'd like to discuss!

**Comment by razum2um** [comment]
@jeffreyjackson I hardly imagine such organization, what will be the profit if we have already a project like https://github.com/sindresorhus/awesome (there are more others) what link to specialised lists. It's already awesome, isn't it?

**Comment by jeffreyjackson** [comment]
We gain value by working together under an organization. 

1. You don't lost control
2.  Your list gets higher visibility and more stars
3.  More people can help manage PRs of you want
4.  We need a place where everyone knows where to go to.  A source of truth. 
5.  Repos will be supported and are less likely to lose traction because it's managed by teams. 
6.  No risk, all awesome.

**Comment by razum2um** [comment]
I'm bit sceptic about that, I don't care too much about stars, traffic and popularity. This repo was primarily created for my own needs, just because bookmarks/github favourites were growing.

Nowadays I'd like to keep it personal because where are really a few PR's (and I clearly realize there wouldn't be as much as for js for example :)  - I value not the amount, but quality and won't miss any personal contact possibilities, while discussing issues and PR's (I know, you mainly specialise in ios/mac, sigh ;)

Anyway, you could try it with other repos from https://github.com/sindresorhus/awesome 
Good luck!

**Comment by jeffreyjackson** [comment]
I understand where you are coming from, we still want you to be the owner of the repository.  While I do specialize in obj-c, I am looking to create a one stop shop for everyone.  Your contribution would be greatly appreciated if you would reconsider.
